name: eclass
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: 8.0.0
  in_app_update: ^4.0.1
  in_app_review: ^2.0.6
  qr_flutter: ^4.0.0
  onesignal_flutter: ^3.5.0
  add_2_calendar: ^2.2.1
  facebook_audience_network: ^1.0.1
  intl_phone_number_input: ^0.7.1
  upi_india: ^3.0.1
  share_plus: ^6.2.0
  flutter_carousel_slider: ^1.1.0
  flutter_facebook_auth: ^5.0.6
  cashfree_pg: ^2.0.12+32
  flutterwave_standard: ^1.0.6
  payu_web_checkout: ^1.0.3
  payhere_mobilesdk_flutter: ^3.0.4
  sqflite: ^2.2.0+3
  path: ^1.8.2
  url_launcher: ^6.1.6
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.0.3
  google_maps_flutter: ^2.2.1
  firebase_analytics: ^10.0.4
  shared_preferences: ^2.0.15
  translator: ^0.1.7
  vimeo_player_flutter: ^0.0.3+2
  loading_overlay: ^0.3.0
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_pdfviewer: ^20.3.56
  provider: ^6.0.4
  font_awesome_flutter: ^10.2.1
  percent_indicator: ^4.2.2
  path_morph: ^1.0.1
  fading_edge_scrollview: ^3.0.0
  http: ^0.13.5
  razorpay_flutter: ^1.3.4
  fluttertoast: ^8.1.1
  page_transition: ^2.0.9
  flutter_secure_storage: ^6.0.0
  flutter_swiper: ^1.1.6
  cached_network_image: ^3.2.2
  image_picker: ^0.8.6
  file_picker: ^5.2.2
  flutter_paystack: ^1.0.7
  youtube_player_flutter: ^8.1.1
  shimmer: ^2.0.0
  dio: ^4.0.6
  http_auth: ^1.0.1
  auto_size_text: ^3.0.0
  html_unescape: ^2.0.0
  sticky_headers: ^0.3.0+2
  paytm: ^3.0.1
  flutter_inappwebview: ^5.7.1
  webview_flutter_wkwebview: ^2.9.5
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  google_sign_in: ^5.4.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  connectivity_plus: ^3.0.2
  audioplayers: ^1.1.1
  better_player: 0.0.83
  video_player: ^2.4.7
  jitsi_meet_wrapper: ^0.0.6

  # Old Versions but do not upgrade.
  flutter_downloader: 1.8.0
  flutter_widget_from_html: 0.8.5
  youtube_player_iframe: 2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/placeholder/
    - assets/i18n/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mada
      fonts:
        - asset: fonts/Mada-Regular.ttf
          weight: 400
        - asset: fonts/Mada-Bold.ttf
          weight: 700
        - asset: fonts/Mada-SemiBold.ttf
          weight: 600
        - asset: fonts/Mada-Medium.ttf
          weight: 500
        - asset: fonts/Mada-Light.ttf
          weight: 300
        - asset: fonts/Mada-Black.ttf
          weight: 800
    - family: icomoon
      fonts:
        - asset: assets/custom_icons/custom-icons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
